services:
  - type: web
    name: rootx-eye
    runtime: image
    repo: https://github.com/rootx-falcon/rootx-eye.git
    plan: free
    envVars:
      - key: PORT
        value: 10000
    dockerCommand: php -S 0.0.0.0:10000
    dockerfilePath: ./Dockerfile
